name: Java CI with SpotBugs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 14
      uses: actions/setup-java@v4
      with:
        java-version: '14'
        distribution: 'temurin'
        cache: 'maven'
    - name: Compile and run with Maven
      run: mvn -B compile
    - name: Run SpotBugs
      run: mvn -B com.github.spotbugs:spotbugs-maven-plugin:spotbugs
